tap "bbc/audiowaveform"
tap "candid82/brew"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jbangdev/tap"
tap "mczachurski/wallpapper"
tap "yqrashawn/goku"
brew "act"
brew "asciinema"
brew "aspell"
brew "bash"
brew "bat"
brew "broot"
brew "fontconfig"
brew "cairo"
brew "cocoapods"
brew "cowsay"
brew "direnv"
brew "duf"
brew "dust"
brew "exa"
brew "exiftool"
brew "fasd"
brew "fd"
brew "ffmpeg"
brew "fortune"
brew "fx"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-extras"
brew "git-flow"
brew "gnupg"
brew "grc"
brew "htop"
brew "httpie"
brew "hub"
brew "hyperfine"
brew "ical-buddy"
brew "jasper"
brew "shared-mime-info"
brew "imagemagick"
brew "jq"
brew "k6"
brew "mas"
brew "maven"
brew "mkcert"
brew "mosquitto"
brew "neovim"
brew "nmap"
brew "nvm"
brew "openconnect"
brew "openvpn"
brew "pango"
brew "php"
brew "pinentry-mac"
brew "poetry"
brew "psutils"
brew "ripgrep"
brew "rust"
brew "speedtest-cli"
brew "subversion"
brew "switchaudio-osx"
brew "telnet"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tree"
brew "watchman"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "bbc/audiowaveform/audiowaveform"
brew "mczachurski/wallpapper/wallpapper"
brew "yqrashawn/goku/goku"
cask "1password"
cask "aerial"
cask "alfred"
cask "android-platform-tools"
cask "android-studio"
cask "appcleaner"
cask "arduino"
cask "audacity"
cask "audio-hijack"
cask "avibrazil-rdm"
cask "balenaetcher"
cask "blender"
cask "brave-browser"
cask "cakebrew"
cask "calibre"
cask "canon-eos-utility"
cask "controlplane"
cask "dash"
cask "dbeaver-community"
cask "discord"
cask "farrago"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "fliqlo"
cask "font-clear-sans"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-monoid"
cask "ganache"
cask "google-chrome"
cask "google-chrome-canary"
cask "handbrake"
cask "hiddenbar"
cask "imageoptim"
cask "insomnia"
cask "intellij-idea-ce"
cask "iterm2"
cask "karabiner-elements"
cask "keka"
cask "loopback"
cask "macdropany"
cask "microsoft-remote-desktop"
cask "microsoft-teams"
cask "mkvtoolnix"
cask "moonlight"
cask "notion"
cask "obs"
cask "obsidian"
cask "podcastmenu"
cask "postman"
cask "projectlibre"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "rancher"
cask "rectangle"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "streamlabs-obs"
cask "stretchly"
cask "sublime-text"
cask "suspicious-package"
cask "telegram"
cask "temurin"
cask "toggl-track"
cask "transmission"
cask "tunnelblick"
cask "ukelele"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
cask "xquartz"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "Home Assistant", id: 1099568401
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "MindNode", id: 1289197285
mas "Next Meeting", id: 1017470484
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Refined GitHub", id: 1519867270
mas "Shareful", id: 1522267256
mas "The Unarchiver", id: 425424353
mas "Twitter", id: 1482454543
mas "Typist", id: 415166115
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
