SPACESHIP_AZURE_SHOW=false
SPACESHIP_KUBECTL_CONTEXT_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_GIT_PREFIX="("
SPACESHIP_GIT_SUFFIX=") "
SPACESHIP_PROMPT_DEFAULT_PREFIX=""
SPACESHIP_PACKAGE_PREFIX="-> "
SPACESHIP_BATTERY_THRESHOLD=20

# Other spaceship plugins
source ~/dotfiles/spaceship/npmrc.plugin.zsh
spaceship add npmrc